# adapted from https://lightrains.com/blogs/deploy-aws-ec2-using-github-actions/
name: deploy
on:
    push: 
        branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      
      - name: Use node 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x  
      
      - name: Install dependencies
        run: npm install

      - name: Deploy to server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
