# adapted from https://medium.com/thelorry-product-tech-data/amazon-ec2-deployment-complete-ci-cd-pipeline-using-github-actions-and-aws-codedeploy-8a477123ff7e
# and https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions

name: deploy
on:
  # push: 
  #     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials" Action for GitHub Actions
          uses: aws-actions/configure-aws-credentials@v4.0.1        
          with:
            role-to-assume: {{ secrets.AWS_ROLE_ARN }}
            aws-region: us-east-2
      # Step 2
        - name: Create CodeDeploy Deployment
          id: deploy
          run: |
            aws deploy create-deployment \
              --application-name application-name \
              --deployment-group-name AppDeploymentGroupName \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
#      - name: Checkout files
#        uses: actions/checkout@v2

#      - name: Deploy to server 1
#        uses: easingthemes/ssh-deploy@main
#        env:
#          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
#          REMOTE_HOST: ${ { secrets.HOST_DNS }}
#          REMOTE_USER: ${ { secrets.USERNAME }}
#          TARGET: ${ { secrets.TARGET_DIR }}
