# adapted from https://lightrains.com/blogs/deploy-aws-ec2-using-github-actions/
name: deploy
on:
  # push: 
  #     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Deploy to server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
