# adapted from https://medium.com/thelorry-product-tech-data/amazon-ec2-deployment-complete-ci-cd-pipeline-using-github-actions-and-aws-codedeploy-8a477123ff7e
# and https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions

name: deploy
on:
  # push: 
  #     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        aws-region: us-east-2
    - name: Create CodeDeploy Deployment
      id: deploy
      run: |
        aws deploy create-deployment \
          --application-name 461Phase2CD \
          --deployment-group-name ec2-deploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
#      - name: Checkout files
#        uses: actions/checkout@v2

#      - name: Deploy to server 1
#        uses: easingthemes/ssh-deploy@main
#        env:
#          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
#          REMOTE_HOST: ${ { secrets.HOST_DNS }}
#          REMOTE_USER: ${ { secrets.USERNAME }}
#          TARGET: ${ { secrets.TARGET_DIR }}
