# adapted from Chombler/CI-demo and hall657/461Project-Phase1
# run tests on pull requests and when pushed to main
name: test
on:
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      
      - name: Use node 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x  
        
      - name: Install dependencies
        run: npm ci
      
      - name: Jest test
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: 0
          LOG_FILE: 'log.txt'
        run: npm test

